In [1]:
import os
import pandas as pd
import pickle
from tqdm import tqdm
import ast

In [3]:
# 1. 개별 데이터프레임을 담을 빈 리스트 생성
df_list = []

for i in range(5):
    # f-string을 이용해 파일 읽기
    df = pd.read_csv(f'./results/LDA_Actor{i}_action_cluster.csv')
    # 리스트에 추가
    df_list.append(df)

# 2. 리스트에 담긴 모든 데이터프레임을 수직(axis=0)으로 합치기
final_df = pd.concat(df_list, ignore_index=True)

In [6]:
# 결과 확인
print(len(final_df))
final_df.head()

58314

,Unnamed: 0,출처,키워드,제목,내용,작성일,링크,tokenized,cluster,action_cluster
0,4,네이버카페_맘이베베,육아질문방,입덧약 처방 받아야 할지 좀 참아볼지 고민입니다,둘째는 입덧이 다르네요 음식을 먹고난 직후가 제일 심하고 냄새에 엄청 예민해지고 체...,2024-12-31,https://cafe.naver.com/f-e/cafes/29434212/arti...,"['입덧_다르다', '다르다_음식', '음식_먹다', '먹다_직후', '직후_심하다...",0,1
1,8,네이버카페_맘이베베,육아질문방,원래 둘째 임신이 더 힘든거에요,찻째 때는 임신 증상 하나도 없었는데 둘째는 입덧 먹덧 허리통증 환도통증 미칠거같네...,2024-12-31,https://cafe.naver.com/f-e/cafes/29434212/arti...,"['찻째_임신', '임신_증상', '증상_입덧', '입덧_먹다', '먹다_덧', '...",0,1
2,12,네이버카페_맘이베베,육아질문방,주차인데 선홍색 피비침 화유일까요,월에도 화유했는데 너무 불안하네요 아침에 눈떠서 소변보는데 피가살짝 비쳐서 일단 출...,2024-12-31,https://cafe.naver.com/f-e/cafes/29434212/arti...,"['화유_불안', '불안_아침', '아침_눈뜨다', '눈뜨다_소변', '소변_피',...",0,1
3,15,네이버카페_맘이베베,육아질문방,임당은 몇주에가서 검사하나요,지금 주인데 주 일에 정밀초음파보려가요 임당은 몇주부터 몇주까지 검사하려가야하나요,2024-12-31,https://cafe.naver.com/f-e/cafes/29434212/arti...,"['주_정밀', '정밀_초음파', '초음파_임', '임_당', '당_검사']",0,2
4,24,네이버카페_맘이베베,육아질문방,인기없는 원장님은 이유가 있네요,간밤에 복통와 출혈로 글썼던 경산모입니다 제가 딱 년전 작년 월에 미즈 에서 다발성...,2024-12-30,https://cafe.naver.com/f-e/cafes/29434212/arti...,"['간밤_복통', '복통_오다', '오다_출혈', '출혈_글', '글_쓰다', '쓰...",0,2

In [8]:
# 1. 컬럼명 변경 (기존 'cluster' -> 'actor_cluster')
final_df = final_df.rename(columns={'cluster': 'actor_cluster'})

# 2. 결과 확인
print(len(final_df))
final_df.head()

58314

,Unnamed: 0,출처,키워드,제목,내용,작성일,링크,tokenized,actor_cluster,action_cluster
0,4,네이버카페_맘이베베,육아질문방,입덧약 처방 받아야 할지 좀 참아볼지 고민입니다,둘째는 입덧이 다르네요 음식을 먹고난 직후가 제일 심하고 냄새에 엄청 예민해지고 체...,2024-12-31,https://cafe.naver.com/f-e/cafes/29434212/arti...,"['입덧_다르다', '다르다_음식', '음식_먹다', '먹다_직후', '직후_심하다...",0,1
1,8,네이버카페_맘이베베,육아질문방,원래 둘째 임신이 더 힘든거에요,찻째 때는 임신 증상 하나도 없었는데 둘째는 입덧 먹덧 허리통증 환도통증 미칠거같네...,2024-12-31,https://cafe.naver.com/f-e/cafes/29434212/arti...,"['찻째_임신', '임신_증상', '증상_입덧', '입덧_먹다', '먹다_덧', '...",0,1
2,12,네이버카페_맘이베베,육아질문방,주차인데 선홍색 피비침 화유일까요,월에도 화유했는데 너무 불안하네요 아침에 눈떠서 소변보는데 피가살짝 비쳐서 일단 출...,2024-12-31,https://cafe.naver.com/f-e/cafes/29434212/arti...,"['화유_불안', '불안_아침', '아침_눈뜨다', '눈뜨다_소변', '소변_피',...",0,1
3,15,네이버카페_맘이베베,육아질문방,임당은 몇주에가서 검사하나요,지금 주인데 주 일에 정밀초음파보려가요 임당은 몇주부터 몇주까지 검사하려가야하나요,2024-12-31,https://cafe.naver.com/f-e/cafes/29434212/arti...,"['주_정밀', '정밀_초음파', '초음파_임', '임_당', '당_검사']",0,2
4,24,네이버카페_맘이베베,육아질문방,인기없는 원장님은 이유가 있네요,간밤에 복통와 출혈로 글썼던 경산모입니다 제가 딱 년전 작년 월에 미즈 에서 다발성...,2024-12-30,https://cafe.naver.com/f-e/cafes/29434212/arti...,"['간밤_복통', '복통_오다', '오다_출혈', '출혈_글', '글_쓰다', '쓰...",0,2

In [9]:
# 'actor_cluster'와 'action_cluster' 컬럼의 결측치 개수 확인
missing_values = final_df[['actor_cluster', 'action_cluster']].isnull().sum()

print(missing_values)

actor_cluster     0
action_cluster    0
dtype: int64

In [10]:
# csv 저장
final_df.to_csv(f'./results/LDA_Actor_Action_cluster_integrated.csv', encoding='utf-8-sig')

In [11]:
final_df['actor_cluster'].value_counts()

actor_cluster
0    18343
1    12938
4    10282
3    10059
2     6692
Name: count, dtype: int64